// <auto-generated />
using BitrixJiraConnector.Api.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitrixJiraConnector.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501000000_AddConfigTables")]
    partial class AddConfigTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.BitrixJiraInfo", b =>
                {
                    b.Property<int>("Bitrix_DealID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Bitrix_DateSearch").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Bitrix_DealLink").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DateTimeCreated").IsRequired().HasColumnType("TEXT");
                    b.Property<long?>("DateTimeSendMailFirst").HasColumnType("INTEGER");
                    b.Property<long?>("DateTimeSendMailSecond").HasColumnType("INTEGER");
                    b.Property<long?>("DateTimeSendMailThird").HasColumnType("INTEGER");
                    b.Property<string>("ErrorInfo").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("HaveError").HasColumnType("INTEGER");
                    b.Property<int>("IsSendDataToJira").HasColumnType("INTEGER");
                    b.Property<int>("IsSendEmail").HasColumnType("INTEGER");
                    b.Property<string>("Jira_Link").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("LastChangeData").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("NumberCheckError").HasColumnType("INTEGER");
                    b.HasKey("Bitrix_DealID");
                    b.ToTable("BitrixJiraInfoes");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.ConfigData", b =>
                {
                    b.Property<int>("ID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("KeyConfig").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ValueConfig").IsRequired().HasColumnType("TEXT");
                    b.HasKey("ID");
                    b.ToTable("ConfigData");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.ExceptionLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("DealID").HasColumnType("INTEGER");
                    b.Property<string>("ExceptionMessage").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ExceptionType").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("LoggedAt").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("StackTrace").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("ExceptionLog");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.SystemConfig", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ConfigKey").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ConfigValue").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.BitrixFieldMapping", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("FieldKey").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("FieldLabel").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("BitrixFieldMappings");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.DealTypeConfig", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("DealTypeId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("DealTypeName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("JiraProjectKey").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("JiraIssueTypeId").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ShouldCreateIssue").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.ToTable("DealTypeConfigs");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.DealTypeRequiredField", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("DealTypeId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("FieldKey").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("DealTypeRequiredFields");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.UserEmailMapping", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("JiraUsername").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("UserEmailMappings");
                });

            modelBuilder.Entity("BitrixJiraConnector.Api.Models.Database.PipelineMapping", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("CategoryId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PipelineName").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("PipelineMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
