// <auto-generated />
using System;
using BitrixJiraConnector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitrixJiraConnector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240704041459_AddFieldTable_BitrixJiraInfo")]
    partial class AddFieldTableBitrixJiraInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BitrixJiraConnector.Models.BitrixJiraInfo", b =>
                {
                    b.Property<int>("Bitrix_DealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bitrix_DateSearch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bitrix_DealLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimeCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DateTimeSendMailFist")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DateTimeSendMailSecond")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DateTimeSendMailThird")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HaveError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSendDataToJira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSendEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jira_Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChangeData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberCheckError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Bitrix_DealID");

                    b.ToTable("BitrixJiraInfoes");
                });

            modelBuilder.Entity("BitrixJiraConnector.Models.ConfigData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ConfigData");
                });

            modelBuilder.Entity("BitrixJiraConnector.Models.ExceptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoggedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExceptionLog");
                });
#pragma warning restore 612, 618
        }
    }
}
