// <auto-generated />
using BitrixJiraConnector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitrixJiraConnector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240618083630_AddTable_BitrixJiraInfo")]
    partial class AddTableBitrixJiraInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BitrixJiraConnector.Models.BitrixJiraInfo", b =>
                {
                    b.Property<int>("Bitrix_DealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bitrix_DateSearch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bitrix_DealLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimeCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HaveError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSendDataToJira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSendEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jira_Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberCheckError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Bitrix_DealID");

                    b.ToTable("BitrixJiraInfoes");
                });
#pragma warning restore 612, 618
        }
    }
}
